site_name: Placetmachine
repo_url: https://github.com/drozzoff/Placetmachine

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.path
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: table
            show_source: false
            allow_inspection: true
            show_root_members_full_path: false
            show_symbol_type_heading: true
            merge_init_into_class: true
            inherited_members: true
            show_signature: true
            show_root_full_path: false
            show_root_heading: true
            signature_crossrefs: true

markdown_extensions:
  - admonition
  - pymdownx.superfences

nav:
  - Main: index.md 
  - 'Documentation':
    - 'Placet module':
      - Communicator: placet/communicator.md
      - Placetpy: placet/pyplacet.md
      - Placet: placet/placetwrap.md
    - 'Lattice module':
      - Element: lattice/element.md
      - Quadrupole: lattice/quadrupole.md
      - Sbend: lattice/sbend.md
      - Multipole: lattice/multipole.md
      - Drift: lattice/drift.md
      - Dipole: lattice/dipole.md
      - Cavity: lattice/cavity.md
      - Bpm: lattice/bpm.md
      - Knob: lattice/knob.md
      - Beamline: lattice/lattice.md
    - 'Beam module':
      - Beam: beam/beam.md
    - Machine: machine.md
  - 'Examples':
    - Example 1: examples/example1.md

