name: Unit-Tests

on:
  push:
    branches:
      - '*'

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install the package
        run: pip3 install .

      - name: Install coverage package
        run: pip3 install coverage

      - name: Run tests with coverage
        run: coverage run -m unittest discover -s tests

      - name: Generate coverage report
        run: coverage report

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
