name: Documentation-Deployment

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Unit-Tests Workflow
        id: check
        uses: actions/github-script@v5
        with:
          script: |
            const { data: runs } = await github.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ci.yml',
              branch: 'master',
              status: 'completed',
              per_page: 1
            });
            if (!runs.workflow_runs.length || runs.workflow_runs[0].conclusion !== 'success') {
              throw new Error('Recent Unit-Tests workflow run was not successful.');
            }

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip3 install mkdocs-material mkdocstrings mkdocstrings-python
      - run: mkdocs gh-deploy --force