name: Documentation-Deployment

on:
  push:
    branches:
      - master
      - PPI-119

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Wait for Unit-Tests to succeed
        id: wait-for-unit-tests
        uses: actions/github-script@v5
        with:
          script: |
            const { owner, repo } = context.repo;
            const commitSha = context.sha;
            let runId;
            while(true) {
              const runs = await github.rest.actions.listWorkflowRunsForRepo({
                owner,
                repo,
                workflow_id: 'ci.yml',
                status: 'completed'
              });
              const run = runs.data.workflow_runs.find(r => r.head_sha === commitSha && r.name === 'Unit-Tests');
              if (run && run.conclusion === 'success') {
                runId = run.id;
                break;
              }
              // Check every 3 seconds
              await new Promise(r => setTimeout(r, 3000));
            }
            return { runId };

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip3 install mkdocs-material mkdocstrings mkdocstrings-python
      - run: mkdocs gh-deploy --force